### ISSUE TITLE
Unable to Style Clock

### ISSUE THREAD

**Issue by jeynergil** [pvoznyuk/react-live-clock#81]
`<Clock
            format={"h:mm:ssa"}
            style={{ fontSize: "24px", color: "green" }}
            ticking={true}
          />`
I just updated the version and the inline CSS stops working.

`<Clock
            format={"h:mm:ssa"}
            ticking={true}
            className="bigclock"
          />`

I also tried this and also didn't work.

Is there any examples how to make it work?

Thanks for your help.

**Comment by anthony0030** [comment]
Try version 5.0.14 both should work now.

**Comment by jeynergil** [comment]
Hi, just tried, already upgraded to "react-live-clock": "^5.0.14", however, still not working. Thanks for the help.

**Comment by anthony0030** [comment]
I think something went wrong in the publish to npm. I added some examples in the source code and they are working. the new version is 5.0.15. How are you importing the script?

**Comment by jeynergil** [comment]
This is how I imported:
import Clock from "react-live-clock";

I tried 5.0.15 and it already works!

Thanks Anthony!

**Comment by anthony0030** [comment]
Cool! Happy to help Jeyner :) Thanks for helping make things better.
